# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config

project_id = "counterhub"

[db]
major_version = 17

[auth]
site_url = "http://localhost:3000"

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]
